### ISSUE TITLE
I cannot use the rtxmlrpc in container:  Config file /root/.rtorrent.rc doesn't exist!

### ISSUE THREAD

**Issue by xyou365** [romancin/rutorrent-flood-docker#100]
Firstly, I ssh into one container,
`docker exec -it rutorrent /bin/sh`
Then, change dir to rtorrent_sess
`cd /config/rtorrent/rtorrent_sess`

Now, I run
`/config/.local/pyroscope/bin/rtxmlrpc d.connection_current CAABAA4C4A8F18A24003099EF7A009A7A7DE2E88` 
to get the status of that torrent. But it tells me
ERROR    Config file '/root/.rtorrent.rc' doesn't exist!

This is my situation Any idea about this?

**Comment by romancin** [comment]
It is explained in the README:

You need to run pyrocore commands with user "abc", which is who runs rtorrent, so use "su - abc" after connecting container before using pyrocore commands.
