### ISSUE TITLE
EACCES: Permission denied scandir /root/.npm

### ISSUE THREAD

**Issue by BoKKeR** [romancin/rutorrent-flood-docker#101]
Flood is having permission problems on my synology. I have set the same guid puid as all my Linuxserver containers use. But it seems that the issue is not with the mounted volumes but the internal /root folder. 
![IMG_20200118_182433_944](https://user-images.githubusercontent.com/2664857/72667778-c9aa4d80-3a1f-11ea-865c-8b3e59ab5781.jpg)

edit: this error happens with no volumes mounted also

**Comment by BoKKeR** [comment]
Very weird, I can run it on almost any machine and it just works, even windows, but on my synology nas it does not work, no matter if I run it from the gui or terminal.

**Comment by shadowking001** [comment]
I have the same issue on an intel NUC.

Docker version : 19.03.7
API version : 1.40

Running the container as root solves the problem, but I'd prefer use another user, is that doable ?

**Comment by kvn1351** [comment]
Same issue on the newest docker on debian.

**Comment by romancin** [comment]
This is solved on the current v4.0.1 tag.
