### ISSUE TITLE
Please add ENV var option to disable ssl.

### ISSUE THREAD

**Issue by kvn1351** [romancin/rutorrent-flood-docker#111]
Hi, many of us don't need ssl and already do so over reverse proxies etc. Please leave us the option to not use ssl.

**Comment by romancin** [comment]
Done. Please, note that if nginx.conf (rutorrent) and config.js (flood) already exists they aren't touched, so delete them before starting container so SSL is not configured.

**Comment by kvn1351** [comment]
Thanks a lot!
