### ISSUE TITLE
plugin rutorrent mobile incorrect folder name and conflict with ipad

### ISSUE THREAD

**Issue by jorritsmit** [romancin/rutorrent-flood-docker#132]
Hi,

as stated in the readme the [rutorrentMobile ](https://github.com/xombiemp/rutorrentMobile) plugin , the name of the plugin folder should be mobile, not rutorrentmobile. Also there is a conflict with the ipad pluging, which i think is deprecated so should be removed or disabled to avoid the conflict i think

**Comment by romancin** [comment]
Thank you for your help on this. The change has been done in PR #136

**Comment by jorritsmit** [comment]
No worries thanks for being so quick to implement.
