### ISSUE TITLE
Search in ruTorrent displays error message

### ISSUE THREAD

**Issue by pwyde** [romancin/rutorrent-flood-docker#135]
When performing search of local torrents in ruTorrent, the following error message is displayed:

`JS error: [https://<ip>/js/webui.js : 2146] TypeError: obj is undefined`

This might be caused by the following reported issue in ruTorrent: [#1989](https://github.com/Novik/ruTorrent/issues/1989)

According to the reported issue above:
> Was caused by https://github.com/Gyran/rutorrent-instantsearch

Looking at the latest commit of the [rutorrent-instantsearch](https://github.com/Micdu70/rutorrent-instantsearch/commit/a3eb30cad3876df312ca479198eb537c7b18cd9b) plugin, it was updated to `version: 1.1`.

Plugin version in rutorrent-flood container is `version: 1.0`.

**Comment by romancin** [comment]
> When performing search of local torrents in ruTorrent, the following error message is displayed:
> 
> `JS error: [https://<ip>/js/webui.js : 2146] TypeError: obj is undefined`
> 
> This might be caused by the following reported issue in ruTorrent: [#1989](https://github.com/Novik/ruTorrent/issues/1989)
> 
> According to the reported issue above:
> 
> > Was caused by https://github.com/Gyran/rutorrent-instantsearch
> 
> Looking at the latest commit of the [rutorrent-instantsearch](https://github.com/Micdu70/rutorrent-instantsearch/commit/a3eb30cad3876df312ca479198eb537c7b18cd9b) plugin, it was updated to `version: 1.1`.
> 
> Plugin version in rutorrent-flood container is `version: 1.0`.

**Comment by romancin** [comment]
Thank you for your issue, I changed it in the image without flood, but kept the old one in this repo. Change already merged in PR #136

**Comment by romancin** [comment]
Thank you for your issue, I changed it in the image without flood, but kept the old one in this repo. Change already merged by PR #136
