### ISSUE TITLE
DataDir plugin cannot move torrent (operation fail) but flood works

### ISSUE THREAD

**Issue by chris-ayala** [romancin/rutorrent-flood-docker#144]
Using the ruTorrent web-GUI, the DataDir plugin fails when trying to use "Save to..." to change the data path of torrents. However, using the flood web-GUI, the "Set Torrent Location", I have no issues.

Is there something wrong with the ruTorrent GUI?

**Comment by romancin** [comment]
Do you see any errors on the log files? It works fine on my instances.

**Comment by chris-ayala** [comment]
It's actually working fine now. I think it was a permissions issue. Not sure why the flood web-GUI was able to perform the move operation though. Anyway, I'll close the issue. Thanks for following up.
