### ISSUE TITLE
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. 

### ISSUE THREAD

**Issue by NoLooseEnds** [romancin/rutorrent-flood-docker#150]
Getting a lot of warnings. Maybe time to update? :)

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support

**Comment by romancin** [comment]
It doesn't depend on me. Pyrocore is only supported on Python v2. Maybe you can give your opinion here:
https://github.com/romancin/rutorrent-flood-docker/issues/159
