### ISSUE TITLE
Change Flood repo?

### ISSUE THREAD

**Issue by NoLooseEnds** [romancin/rutorrent-flood-docker#160]
The original Flood project is more or less dead, but [@jesec has picked up the torch ](https://github.com/jesec/flood) and is actively making improvements.

Would it be possible to change to his repo?

**Comment by bjeanes** [comment]
I also would like to see this. IN particular I want to take advantage of some new config options which allow me to avoid creating a user (as I already have my reverse proxy handling auth):

```js
  disableUsersAndAuth: true,
  configUser: {
    client: 'rTorrent',
    type: 'socket',
    version: 1,
    socket: '/run/php/.rtorrent.sock',
  },
```

**Comment by romancin** [comment]
Done.
https://github.com/romancin/rutorrent-flood-docker/pull/162
