### ISSUE TITLE
Flood: Failed to access runtime directory

### ISSUE THREAD

**Issue by Flupster** [romancin/rutorrent-flood-docker#166]
Starting the the container with PUID/GUID with anything other than 0 causes flood to not start with this error

```
> flood@3.1.0 start /usr/flood
> node --use_strict dist/index.js "--host" "0.0.0.0" "--port" "3000"
 
Failed to access runtime directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@3.1.0 start: `node --use_strict dist/index.js "--host" "0.0.0.0" "--port" "3000"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flood@3.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I had a peak inside to see if I could figure it out but found nothing, the db isn't being generated at all in /config/flood-db so possibly the issue?

Also flood is now on v4.2.0 as of this issues while this image is only at v3.1.0 perhaps an update would be good too

**Comment by Flupster** [comment]
Here's an example docker-compose file that causes the error

```YAML

version: "2"
services:
  rutorrent:
    image: romancin/rutorrent-flood:latest
    container_name: rutorrent-flood
    networks:
      - default
    tty: true
    volumes:
      - /share/Container/rutorrent-flood:/config
      - /share/Container/rutorrent-flood/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CREATE_SUBDIR_BY_TRACKERS=NO
      - SSL_ENABLED=NO
      - RT_TOKEN=
      - RT_MASTERS=
    ports:
      - "8880:80"
      - "32316:52316"
      - "3333:3000"
```

**Comment by djl0** [comment]
I'm getting the same error

**Comment by vavdagic** [comment]
Same here, flood cannot start on any PUID PGID different than 0, and on ID 0 fails to persist flood settings. On container recreate all settings are gone

**Comment by pwyde** [comment]
I can also confirm the same behaviour. I've performed some troubleshooting but without any interesting findings. Unfortunately my knowledge regarding flood is very limited compared to rtorrent.

**Comment by zxsix** [comment]
Same issue with flood.  standing by for a fix.

**Comment by ADRFranklin** [comment]
There is a way to fix this, by entering the container as root and going to `/var/run/s6/services/flood/` editing the file `run` and adding `--rundir=/usr/flood` to the end of the npm line.

You might also need to do `chown -R abc:users /usr/flood` 

you would need to do this every time you restart the container, but it's a temp way to make it work until it is fixed.

**Comment by pwyde** [comment]
> There is a way to fix this, by entering the container as root and going to `/var/run/s6/services/flood/` editing the file `run` and adding `--rundir=/usr/flood` to the end of the npm line.
> 
> You might also need to do `chown -R abc:users /usr/flood`
> 
> you would need to do this every time you restart the container, but it's a temp way to make it work until it is fixed.

Thank you! That solved the issue, even tough it does not survive container restart. Better than nothing.

**Comment by vavdagic** [comment]
Can you please add this fix to the image @romancin ?

**Comment by jotosmurf** [comment]
Same here. Also, the proposed fix is indeed very temporary as a repetitive manual intervention is needed which defeats the purpose of automation.

**Comment by maqdev** [comment]
Here's PR to fix this issue. Until it's built you can use this image maqdev/rutorrent-flood-docker:0.9.9

**Comment by jotosmurf** [comment]
Thank you very much @maqdev. I dunno whether this repository is still being updated by @romancin. No sign of life for 6+ months now.
