### ISSUE TITLE
Flood not working "ERR_CONNECTION_REFUSED"

### ISSUE THREAD

**Issue by runaroundhome** [romancin/rutorrent-flood-docker#18]
Was working fine till the refresh you made yesterday.

**Comment by romancin** [comment]
I know, it seems flood has changed the way to install it, I am working on fixing it.

**Comment by runaroundhome** [comment]
Legend!

**Comment by romancin** [comment]
Sorry for the delay, but this one has been difficult to fix, finally I got it. 0.9.4 and master images are building right now, in 2 hours you should see them. Enjoy!
