### ISSUE TITLE
Can't create new account on first run

### ISSUE THREAD

**Issue by jeansebb** [romancin/rutorrent-flood-docker#23]
Using flood
View logs:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle flood@1.0.0~prestart: flood@1.0.0
6 info lifecycle flood@1.0.0~start: flood@1.0.0
7 verbose lifecycle flood@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle flood@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/flood/node_modules/.bin:/usr/bin:/usr/sbin:/bin:/sbin
9 verbose lifecycle flood@1.0.0~start: CWD: /usr/flood
10 silly lifecycle flood@1.0.0~start: Args: [ '-c', 'node server/bin/start.js' ]
11 silly lifecycle flood@1.0.0~start: Returned: code: 132  signal: null
12 info lifecycle flood@1.0.0~start: Failed to exec start script
13 verbose stack Error: flood@1.0.0 start: `node server/bin/start.js`
13 verbose stack Exit status 132
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid flood@1.0.0
15 verbose cwd /usr/flood
16 verbose Linux 4.4.0-109-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 132
22 error flood@1.0.0 start: `node server/bin/start.js`
22 error Exit status 132
23 error Failed at the flood@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 132, true ]

Don't know what is causing this.

Thx

**Comment by romancin** [comment]
I have just tried it with an empty configuration directory and it initialized the config file correctly, cannot reproduce this error. Are you using the latest image version?

**Comment by jeansebb** [comment]
Affirmative, It is a brand new config with the latest version. I wanted to give rtorrent+flood a go. I'll stay with other tool.

Thx
