### ISSUE TITLE
additional folder access for watch and completed

### ISSUE THREAD

**Issue by dogboy23** [romancin/rutorrent-flood-docker#37]
I'm trying to create additional folder access mappings for a watch folder and a completed downloads folder, but I can't access them through the FS... is there a simple way to address this. Current solution involves mapping a higher folder, but that exposes unwanted elements of the file system to ruTorrent

TIA

**Comment by romancin** [comment]
I have not understand you really well. I have mapped FS under /downloads directory. This is my docker compose file for reference:

rutorrent-flood_service:
    #image: romancin/rutorrent-flood:develop
    image: romancin/rutorrent-flood:0.9.4
    container_name: rutorrent-flood
    networks:
      - traefik
    dns:
      - 8.8.8.8
      - 8.8.4.4
    tty: true
    volumes:
      - /share/Container/rutorrent-flood:/config
      **- /share/Descargas_Disco3:/downloads
      - /share/Descargas_Disco1:/downloads/DISCO1
      - /share/Descargas_Disco2:/downloads/DISCO2
      - /share/Descargas_Disco4:/downloads/DISCO4**
      # - /share/Descargas_Disco5:/downloads/DISCO5
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
      - TZ=${TZ}
    ports:
      - "9443:443"
      - "62316:62316"
      - "3000:3000"

Is this what you want to do? Apply the same logic for watch directories, but remember to add them to rtorrent.rc file.

**Comment by dogboy23** [comment]
Thanks for the advice, I didn’t realise you could map to subfolders. All ok
now.

**Comment by romancin** [comment]
👍👍
