### ISSUE TITLE
Update rtorrent to 0.9.7?

### ISSUE THREAD

**Issue by Talent30** [romancin/rutorrent-flood-docker#40]
rtorrent released version 0.9.7
https://github.com/rakshasa/rtorrent/releases

**Comment by romancin** [comment]
I will create this version when it become supported on the majority of the private trackers I use. I will keep you informed.

**Comment by romancin** [comment]
Coming soon 🙂

**Comment by romancin** [comment]
Done.

**Comment by ShagoY** [comment]
@romancin 
In your "readme rutorrent-flood", you put "romancin/rutorrent:latest" instead of "romancin/rutorrent-flood:latest"

**Comment by romancin** [comment]
Corrected, thank you.
