### ISSUE TITLE
Time to wait after install?

### ISSUE THREAD

**Issue by bonk1990** [romancin/rutorrent-flood-docker#42]
Hi, should I wait some time after cointeiner start? Waiting for rtorrent do be compiled or somthing like that?
I'm asking becouse of this:
https://i.imgur.com/gWVzslZ.png
https://i.imgur.com/3feYcOu.png

**Comment by smathev** [comment]
Hi.

If you run the command "docker logs [name of rutorrent-flood-docker container]" you will see where the docker is currently at, whether it's done rebuilding or not.

In my experience, it always runs the file 30-getautodl and that always takes some time. I haven't fully investigated why that is, I've simply come to accept it.

There isn't, in my view, a set time to way, but if it hasn't finished after 30-60 seconds (maybe more, depending on what system and internet connection you are on) I would try restarting the container.

**Comment by romancin** [comment]
The first run creates Diffie-Hellman handshake for nginx ssl. It can take a lot of time depending on your cpu.

**Comment by romancin** [comment]
I don’t see the images. If you still have the problem, feel free to write here. I close this issue for the moment.
