### ISSUE TITLE
how to automate rtcontrol tasks

### ISSUE THREAD

**Issue by ilieash** [romancin/rutorrent-flood-docker#43]
currently use as cron job. just wondering if u have any simple suggestion to run these command inside container periodically. 
 example:
/rtcontrol --from-view started is_complete=yes --delete --yes

Thanks alot for your effort.

**Comment by romancin** [comment]
Why don’t you use the docker host crontab? You can create a simple script like `docker exec container name “rctontrol args”`.

**Comment by DFDC** [comment]
Hey Romancin,

How would we pass these through as user ABC? I've tried this

```
$ docker exec --user abc rutorrent-flood /config/.local/pyroscope/bin/rtcontrol is_complete=yes
ERROR    Config file '/root/.rtorrent.rc' doesn't exist!
INFO     Total time: 0.016 seconds.
```

and get the result above. abc has a $UID of 0, which is shared with root. I'm investigating whether I want to migrate my services from lxc to docker and trying to iron out any issues on a vps before I deploy dockstarter+your project!

Thank you

**Comment by DFDC** [comment]
I got it working by changing the HOME dir in portainer from /root to /config
Might be a bad fix, we'll see.
