### ISSUE TITLE
Problema al reiniciar

### ISSUE THREAD

**Issue by alebupal** [romancin/rutorrent-flood-docker#44]
Buenas @romancin 
ya utilizaba tu docker antiguo de rtorrent, lo descubrí en el grupo de xpenology.
He instalado este y todo va bien, excepto cuando reinicio el servidor.
Al reiniciar no conecta con rtorrent:
` Error downloading files. Make sure autodl-irssi is started and configured properly (eg. password, port number): Error getting files listing: Error: Could not connect: (111) Connection refused`

`Torrent list not yet available, connection to rTorrent not established.`

http://prntscr.com/l6uh9d

Parece que no encuentra el archivo .rtorrent.rc.
Actualmente lo tengo en un hp g8 con xpenology - DSM 6.2-23739 Update.
Un saludo y gracias!

**Comment by B1T3S** [comment]
Buenos días,

Antes de nada comentar que el docker de rutorrent va muy bien, gracias @romancin, lo estoy usando en un NAS Synology. 

Pero el problema es que me pasa exactamente lo mismo que @alebupal, reiniciando el docker no pasa pero una vez se reinicia DSM deja de funcionar.

Un saludo.

**Comment by romancin** [comment]
Apagáis el contenedor manualmente antes de reiniciar la NAS? El detach crea 2 ficheros de lock, uno para rtorrent y otro para el irssi. Si reiniciáis directamente y al contenedor no le da tiempo a apagarse, esos lock se quedan impidiendo por seguridad el arranque. Borrad el contenedor y volvedlo al crear con los mismos mapeos para que vuelva a funcionar.

**Comment by alebupal** [comment]
> Apagáis el contenedor manualmente antes de reiniciar la NAS? El detach crea 2 ficheros de lock, uno para rtorrent y otro para el irssi. Si reiniciáis directamente y al contenedor no le da tiempo a apagarse, esos lock se quedan impidiendo por seguridad el arranque. Borrad el contenedor y volvedlo al crear con los mismos mapeos para que vuelva a funcionar.

Entonces es por eso, no apago el contenedor. Al reiniciar el NAS no he tocado nada de docker.
He borrado el contenedor (no eliminado) y ya funciona correctamente, al mapear configuración y descargas todo se queda exactamente igual.
un saludo!

**Comment by romancin** [comment]
Cierto, la opción de Borrar de Synology recrea el contenedor limpio. Me alegro de que vuelva a funcionar. Cierro el issue entonces.
