### ISSUE TITLE
geoip plugin

### ISSUE THREAD

**Issue by B1tl0rd** [romancin/rutorrent-flood-docker#45]
Thanks
cannot see the country flag..
the plugin php extension is necessary?

**Comment by romancin** [comment]
The plugin works fine, but you should configure docker network accordingly. With NAT, source IPs are not seen well. Use host/macvlan networks.

**Comment by ShagoY** [comment]
Hi @romancin 

I used another image up to yours (until I wanted to test Flood) and I had opened an "exit" to repair the Geoip plugin.
The maintainer has made a patch that you can find here: 
https://github.com/xataz/docker-rtorrent-rutorrent/pull/19

With your image, I have the GeoIP plugin enabled and loaded but no display.
I already use the "host networks".

Thank you in advance.

**Comment by romancin** [comment]
Thank you for the suggestions. There is more work to do looking at that repo. Will consider this when I have spare time.

**Comment by romancin** [comment]
Done:
v2.0.1 (29/04/2019): Added GeoIP2 plugin.
