### ISSUE TITLE
$scgi_port y $scgi_host

### ISSUE THREAD

**Issue by guiniguada** [romancin/rutorrent-flood-docker#46]
Hola, primero darte las gracias por tu trabajo. No consigo que me funcione correctamente, me sale este error:

02.11.2018 14:26:12] Sin conexión a rTorrent. Compruebe si se encuentra ejecutado. Verifique $scgi_port y $scgi_host en config.php y scgi_port en el archivo de configuración de rTorrent.

Ubuntu Server 18.04

rtorrent.log:

1541163915 C Caught exception: 'Failed to parse command line option: Error in option file: /config/rtorrent/rtorrent.rc:166: Bad return code.'.

config.php:

$scgi_port = 0;
$scgi_host = "unix:////run/php/.rtorrent.sock";

rtorrrent.rc:

network.scgi.open_local = /run/php/.rtorrent.sock

Si necesitas mas info, te la aporto.

Un saludo.

**Comment by themightykitten** [comment]
It is Pyrocore that is preventing rtorrent from starting at all because of a bad config in rtorrent.rc
As a temporary fix, omment out everything regarding Pyrocore in the rtorrent.rc file

**Comment by romancin** [comment]
Could you please test with the new images? It should have been fixed now.

**Comment by guiniguada** [comment]
Hello, if it works correctly. I have it currently installed on Ubuntu Server 18.04.2.

Thanks and best regards

**Comment by romancin** [comment]
Thank you for testing! Closing this.
