### ISSUE TITLE
Mover descargas finalizadas

### ISSUE THREAD

**Issue by alebupal** [romancin/rutorrent-flood-docker#47]
Buenas,
Estoy intentando configurar rutorrent para que haga esto y no hay manera, y no encuentro apenas documentación en internet o no me entero bien de lo que veo.

Quiero crear la siguiente estructura de carpetas:
Downloads: watch , incoming, completed, m1, m2, m3
m1: watch , incoming, completed
m2: watch , incoming, completed
m3: watch , incoming, completed

m1,m2 y m3 son carpetas que están en otros discos duros.

Esto ya lo tengo, he editado el fichero  /etc/cont-init.d/20-config quitando las carpetas de los trackers:
`
mkdir -p\ /config{/log/nginx,/log/rtorrent,/log/rutorrent,/nginx,/nginx/conf.d,/php,/rtorrent/rtorrent_sess,/rutorrent/settings/users,/.irssi,/flood} \                            
        /config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \                                                                                                            
        /downloads/{completed,incoming,watched} \                                                                                                                                
        /downloads/m1/{completed,incoming,watched} \                                                                                                                             
        /downloads/m2/{completed,incoming,watched} \                                                                                                                             
        /downloads/m3/{completed,incoming,watched} \                                                                                                                             
        /run{/nginx,/php} \                                                                                                                                                      
        /var/lib/nginx/tmp/client_body
`
Y sus permisos:
`
chown abc:abc \                                                                                                                                                                  
        /downloads \                                                                                                                                                             
        /downloads/{completed,incoming,watched,m1,m2,m3} \                                                                                                                       
        /downloads/m1/{completed,incoming,watched} \                                                                                                                             
        /downloads/m2/{completed,incoming,watched} \                                                                                                                             
        /downloads/m3/{completed,incoming,watched} \                                                                                                                                          
`

Y yo querría que cuando una descarga finaliza se mueva a su respectiva carpeta de finalizadas. Es decir, si está en downloads/incoming la nueva a downloads/completed y si está en downloads/m1/incoming la mueva a downloads/m1/completed
Se que es editando el rtorrent.rc en la parte de 
`# Move the downloaded data to the tracker directory beï¿½low Downloads`
he probado unas cuantas cosas que he visto y no hay manera

Igual con sus respectivos watch, aunque tengo puesto estoy no se si lo estoy haciendo bien:
`schedule = watch_directory_99,5,5,"load_start=/downloads/watched/*.torrent,\"d.set_custom=auto,/downloads/incoming/\""`
`schedule = watch_directory_98,5,5,"load_start=/downloads/m1/watched/*.torrent,\"d.set_custom=auto,/downloads/m1/incoming/\""`
`schedule = watch_directory_97,5,5,"load_start=/downloads/m2/watched/*.torrent,\"d.set_custom=auto,/downloads/m2/incoming/\""`
`schedule = watch_directory_96,5,5,"load_start=/downloads/m3/watched/*.torrent,\"d.set_custom=auto,/downloads/m3/incoming/\""`

A ver si me puedes aclarar algo, un saludo y gracias!

**Comment by alebupal** [comment]
He avanzado algo en los watch tengo esto :
`schedule = watch_directory_99,5,5,"load_start=/downloads/watched/*.torrent,\"d.set_custom=auto,/downloads/completed/\""`
`schedule = watch_directory_98,5,5,"load_start=/downloads/m1/watched/*.torrent,\"d.set_custom=auto,/downloads/m1/completed/\""`
`schedule = watch_directory_97,5,5,"load_start=/downloads/m2/watched/*.torrent,\"d.set_custom=auto,/downloads/m2/completed/\""`
`schedule = watch_directory_96,5,5,"load_start=/downloads/m3/watched/*.torrent,\"d.set_custom=auto,/downloads/m3/completed/\""`

y en la parte de mover, he dejado el que hay por defecto.
Lo único que me falta es que siempre que se está descargando algo va a la carpeta /downloads de la raíz y yo quiero que vaya a su respectiva carpeta incoming, sigo investigando...

**Comment by alebupal** [comment]
Ya está, conseguido!
He añadido un campo más al watch
`schedule = watch_directory_99,5,5,"load_start=/downloads/watched/*.torrent,\"d.directory.set=/downloads/incoming/\",\"d.set_custom=auto,/downloads/completed/\""`
`schedule = watch_directory_98,5,5,"load_start=/downloads/m1/watched/*.torrent,\"d.directory.set=/downloads/m1/incoming/\",\"d.set_custom=auto,/downloads/m1/completed/\""`
`schedule = watch_directory_97,5,5,"load_start=/downloads/m2/watched/*.torrent,\"d.directory.set=/downloads/m2/incoming/\",\"d.set_custom=auto,/downloads/m2/completed/\""`
`schedule = watch_directory_96,5,5,"load_start=/downloads/m3/watched/*.torrent,\"d.directory.set=/downloads/m3/incoming/\",\"d.set_custom=auto,/downloads/m3/completed/\""`

**Comment by RaymondSchnyder** [comment]
It would help to post the information in english, as not everyone speaks spanish.

**Comment by alebupal** [comment]
@RaymondSchnyder Hello,
My English is not very good but I am going to try it.
if you want the downloads to move automatically.
You have to edit this file /etc/cont-init.d/20-confi to add the folders and remove the folders from the trackers:
http://prntscr.com/may57o
`mkdir -p \
	/config{/log/nginx,/log/rtorrent,/log/rutorrent,/nginx,/nginx/conf.d,/php,/rtorrent/rtorrent_sess,/rutorrent/settings/users,/.irssi,/flood} \
	/config/rutorrent/profiles{/settings,/torrents,/users,/tmp} \
	/downloads/{completadas,descargando,descargar} \
	/downloads/m1/{completadas,descargando,descargar} \
	/downloads/m2/{completadas,descargando,descargar} \
	/downloads/m3/{completadas,descargando,descargar} \
	/run{/nginx,/php} \
	/var/lib/nginx/tmp/client_body`

where "completadas" are the finished downloads, "descargando" are the downloads that are in progress and  "descargar" is where you put the .torrent to download.
m1, m2 and m3 are additional folder. (https://github.com/romancin/rutorrent-flood-docker/issues/37)

Finally you have to edit the rtorrent.rc http://prntscr.com/may900

`# General watch directory
schedule = watch_directory_99,5,5,"load_start=/downloads/descargar/*.torrent,\"d.directory.set=/downloads/descargando/\",\"d.set_custom=auto,/downloads/completadas/\""
schedule = watch_directory_98,5,5,"load_start=/downloads/m1/descargar/*.torrent,\"d.directory.set=/downloads/m1/descargando/\",\"d.set_custom=auto,/downloads/m1/completadas/\""
schedule = watch_directory_97,5,5,"load_start=/downloads/m2/descargar/*.torrent,\"d.directory.set=/downloads/m2/descargando/\",\"d.set_custom=auto,/downloads/m2/completadas/\""
schedule = watch_directory_96,5,5,"load_start=/downloads/m3/descargar/*.torrent,\"d.directory.set=/downloads/m3/descargando/\",\"d.set_custom=auto,/downloads/m3/completadas/\""`

a greeting!

**Comment by romancin** [comment]
Great! Closing issue.
