### ISSUE TITLE
Pyrocore: rtorrent.rc returns an error code because of it, rtorrent never starts

### ISSUE THREAD

**Issue by themightykitten** [romancin/rutorrent-flood-docker#49]
Hi,

Since the addition of Pyrocore the rtorrent.rc file is fucked.

This prevents rtorrent from starting at all, which is the reason behind the recent issues #48 #46

**Comment by romancin** [comment]
Could you please test with the new images? It should have been fixed now.

**Comment by romancin** [comment]
Closing. Confirmed it works on issue #46
