### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by nzjoshellis** [romancin/rutorrent-flood-docker#51]
Is it possible to get IPv6 support added? 

I believe that '--enable-ipv6' just needs to be added to the rtorrent setup.

**Comment by romancin** [comment]
Cannot test this as my ISP uses IPv4. Can you fork my repo and test it?

**Comment by romancin** [comment]
> Is it possible to get IPv6 support added?
> 
> I believe that '--enable-ipv6' just needs to be added to the rtorrent setup.

Could you please make a fork of my project adding that flag and trying it? If you tell me it works, I will change it on the main code. Thank you!

**Comment by zuosc** [comment]
can tell me where to add '--enable-ipv6'   setting in dockerfile?  I can test it!

**Comment by zuosc** [comment]
I find this:
```
著作权归作者所有。
商业转载请联系作者获得授权，非商业转载请注明出处。
作者：Rhilip
链接：https://blog.rhilip.info/archives/754/
来源：https://blog.rhilip.info/

cd /tmp
curl http://rtorrent.net/downloads/libtorrent-0.13.4.tar.gz | tar xz
cd libtorrent-0.13.4
wget https://github.com/QuickBox/QB/raw/master/setup/sources/libtorrent-0.13.4-tar.patch
patch -p1 < libtorrent-0.13.4-tar.patch
./autogen.sh
./configure --enable-ipv6
make
sudo make install
```

**Comment by zuosc** [comment]
OK.  if I use rtorrent/0.9.7/0.13.7, it has IPV6 support. 

0.9.4 do not have

**Comment by romancin** [comment]
Thank you for advise! Closing this.
