### ISSUE TITLE
AddZip & mediastream Plugin issue

### ISSUE THREAD

**Issue by chewlm86** [romancin/rutorrent-flood-docker#52]
Hi,

I am running on synology docker with the latest image.
I got the following plugin error on the console.

`plugins.js:190 Plugin 'AddZip': localization for 'en' not found.`

`Refused to execute script from 'http://mydomain/plugins/mediastream/settings.js.php' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

Best Regards,
Chew

**Comment by romancin** [comment]
Cannot reproduce this. Could you please in the first place with the current images? Thank you.

**Comment by chewlm86** [comment]
Thanks, the latest version resolved this issue.

**Comment by romancin** [comment]
Awesome, thank you for notifying!
