### ISSUE TITLE
Error installing flood on Windows docker

### ISSUE THREAD

**Issue by mdkozlowski** [romancin/rutorrent-flood-docker#68]
Running Windows 10 Education & Docker 18.09.2
rutorrent and rtorrent work correctly but flood outputs this into logs every 1s indefinitely:
```
> flood@1.0.0 start /usr/flood
> node server/bin/start.js

/usr/flood/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

Error: Failed to flush to storage
    at /usr/flood/node_modules/nedb/lib/storage.js:63:19
    at /usr/flood/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flood@1.0.0 start: `node server/bin/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flood@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-02T21_29_45_458Z-debug.log

```
Would this have to be changed on floods side?

**Comment by romancin** [comment]
Sorry, but I don't have a Windows box to test it. Maybe someone else can try, or you can open an issue on flood project.

**Comment by Austin76016** [comment]
This appears to be due to an issue with the database that flood is using and is actually a bug with node itself on non Linux hosts. For anyone who comes here in the future. I think flood would need to switch database software used or njs team need to fix an issue they dont seem to want to fix.
