### ISSUE TITLE
Forgets socket between restarts

### ISSUE THREAD

**Issue by pmow** [romancin/rutorrent-flood-docker#69]
Hello,

I'm having an issue where socket gets forgotten between restarts of the container.  I tried looking at logs, and the only item was the following error:

    npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
    npm ERR!  { Error: EACCES: permission denied, scandir '/root/.npm/_logs'
    npm ERR!   stack: 'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
    npm ERR!   errno: -13,
    npm ERR!   code: 'EACCES',
    npm ERR!   syscall: 'scandir',
    npm ERR!   path: '/root/.npm/_logs'

Are these errors related at all to the socket being forgotten?  I've checked the flood config file, and the correct socket is there.

**Comment by romancin** [comment]
I can't reproduce this, sorry. Do you stop cleanly container?

**Comment by pmow** [comment]
Yes.  Have even recreated the container without config (from scratch).  Continues to happen.

**Comment by hexed** [comment]
I am  getting this same issue.

**Comment by Tetrokun** [comment]
I'm also having this issue, But I think It's permissions related. 
I went from running the container as UID 0 GID 0 and changed it to G:100 U:99 now it's giving a fit.

**Comment by romancin** [comment]
Solved on current v4.0.1 image.
