### ISSUE TITLE
Remove Torrent & Save to option not working in ruTorrent

### ISSUE THREAD

**Issue by chewlm86** [romancin/rutorrent-flood-docker#70]
Hi,

I found that the Remove option (the one without the Delete Data) will delete the Torrent & Data.
Shouldn't this only delete the torrent while remaining the downloaded files?

And i also found that the Save to option (with Move Data & fast resume checked) will remove the old data and begin download at the new folder.

I lost a couple of file when using these option, ouch...

Best Regards,
Chew

**Comment by romancin** [comment]
For the first one, comment this line on rtorrent.rc file:

# Erase data when torrent deleted (no need erasedata plugin on ruTorrent)
method.set_key = event.download.erased,delete_erased,"execute=rm,-rf,--,$d.data_path="

About the second one, I am trying to reproduce it without success.

**Comment by romancin** [comment]
Commented out on the image. Closing this.
