### ISSUE TITLE
Problema con RuTorrent y Docker

### ISSUE THREAD

**Issue by Merovinquio** [romancin/rutorrent-flood-docker#74]
Buenos días, me da los siguientes errores en Rutorrent corriendo como imagen en Docker:

[30.04.2019 12:37:26] WebUI started.
[30.04.2019 12:37:27] Sin conexión a rTorrent. Compruebe si se encuentra ejecutado. Verifique $scgi_port y $scgi_host en config.php y scgi_port en el archivo de configuración de rTorrent.
[30.04.2019 12:37:27] _cloudflare: El Plugin no funcionará. El Webserver no puede acceder al programa externo (python).
[30.04.2019 12:37:27] _task: El Plugin no funcionará. El Webserver no puede acceder al programa externo (pgrep).
[30.04.2019 12:37:27] create: El Plugin no funcionará. Requiere el plugin(s) _task

¿Alguna idea? Gracias de antemano.

**Comment by romancin** [comment]
Has realizado lo indicado en las notas marcadas como importantes del README? Por ese error, tiene pinta de que estás utilizando archivos de configuración antiguos con la última versión de la imagen. Renombra los indicados en el README y prueba a reiniciar.

**Comment by Merovinquio** [comment]
Buenas, he llegado incluso a borrar completamente las carpetas de config y download, borrar también el contenedor e incluso volver a bajar la imagen, pero nada.

**Comment by romancin** [comment]
Cuando puedas, pega el log de la salida de rtorrent, está dentro de /config/logs/rtorrent.log

**Comment by Merovinquio** [comment]
Claro, aquí está:

1556628870 C Caught exception: 'Failed to parse command line option: Error in option file: /config/rtorrent/rtorrent.rc:22: Command "peer_exchange" does not exist.'.

**Comment by romancin** [comment]
Indica claramente que en la línea 22 del fichero de configuración de rtorrent, el comando peer_exchange no existe. Estás utilizando un fichero de configuración antiguo. Si accedes aquí:

https://github.com/romancin/rutorrent-flood-docker/blob/14b84214a866c40f5582fb189a69cfcc225c2150/root/defaults/rtorrent.rc

Mira la línea 22 y verás que está igual que el tuyo. Como he comentado, tienes que borrar el fichero con las nuevas imágenes, de lo contrario al arrancar rtorrent fallará. Puedes probar con el tag de imagen 0.9.6-v2.0.1? Probablemente funcione, y corroborará lo que te comento.

**Comment by Merovinquio** [comment]
Pues efectivamente, he seguido los pasos que me has dicho y ya puedo ver la interfaz de RuTorrent. Ahora me están haciendo cosas raras los torrents que tenía por completar, como ponerse en pausa solos o no contarme para el sedeo en los trackers, aunque supongo que eso será más normal.

Muchas gracias por la ayuda :) 👍

**Comment by romancin** [comment]
Normal no es, comprueba que el mapeo de los directorios persistentes es exactamente el mismo. Si se te pausan es porque no está encontrando los ficheros en disco probablemente.

**Comment by Merovinquio** [comment]
Si, me refería a que a priori eso ya es más sencillo. Voy a hacer unas pruebas para lo del mapeo. Muchas gracias por todo :)
