### ISSUE TITLE
Flood behind traefik

### ISSUE THREAD

**Issue by MikeMatau** [romancin/rutorrent-flood-docker#75]
I'm running flood behind a traefik reverse proxy that adds ssl to everything.
Is it possible to have an option to disable the ssl in nginx so I can just run it locally and have the reverse proxy handle everything?

**Comment by ag0r4n** [comment]
Just don't expose the port, disable certificate validation in traefik.toml :

`insecureSkipVerify = true` 
  
Compose setup :
 labels:
      - "traefik.enable=true"

      - "traefik.flood.frontend=flood"
      - "traefik.flood.domain=flood.example.com"
      - "traefik.flood.port=3000"
      - "traefik.flood.frontend.rule=Host:flood.example.com"
      - "traefik.flood.protocol=https"

      - "traefik.ruttorent.frontend=rutorrent"
      - "traefik.ruttorent.domain=rutorrent.example.com"
      - "traefik.rutorrent.port=443"
      - "traefik.rutorrent.frontend.rule=Host:rutorrent.example.com"
      - "traefik.rutorrent.protocol=https"

**Comment by romancin** [comment]
Thank you for the solución!!
