### ISSUE TITLE
Problema Autodescarga Regla

### ISSUE THREAD

**Issue by javimarinakis** [romancin/rutorrent-flood-docker#80]
Buenas tardes.
He observado un problema y no sé si es un tema relacionado con permisos. Tengo la versión 0.9.6 instalada sobre un contenedor en un disco SSD. Las descargas la tengo automatizadas para en 2 capetas: pelis y series. Las descargas están ubicadas en un disco SATA. Resulta que cuando configuro la autodescarga en /media/sata/pelis o /media/sata/series no me lo aloja en dichas carpetas, Me lo deja en la raíz /download, osea en /media/sata. Me resulta raro ya que cuando cargo manualmente un torrent a dichas carpetas funciona sin problemas. He cambiado los permisos root a usuario y grupo también. puid y pgid a usuario. Aparte no me deja cambiar la ruta de descargas una vez finalizado. No sé qué hacer más.

**Comment by romancin** [comment]
Prueba con la imagen actual borrando el rtorrent.rc de tu directorio persistente. Un compañero detectó un problema con las reglas de automove y está arreglado desde hace algunas versiones. Tu problema puede estar relacionado con esto. Si te sigue sin funcionar coméntalo aquí y reabro el issue.
