### ISSUE TITLE
_cloudflare plugin: cloudscraper module can't be loaded in Python

### ISSUE THREAD

**Issue by chewlm86** [romancin/rutorrent-flood-docker#81]
Hi,

I get this error message in ruTorrent Log on the latest version.

_cloudflare plugin: cloudscraper module can't be loaded in Python

Might be due to this?
https://github.com/linuxserver/docker-rutorrent/issues/112
https://github.com/linuxserver/docker-rutorrent/pull/116

Best Regards,
Chew

**Comment by romancin** [comment]
Fixed on the current image.
