### ISSUE TITLE
xmlrpc-c SVN

### ISSUE THREAD

**Issue by zuosc** [romancin/rutorrent-flood-docker#87]
http://svn.code.sf.net/p/xmlrpc-c/code/stable xmlrpc-c  

this address is not very stable。 

Is it possible to use github address:  https://github.com/mirror/xmlrpc-c.git

**Comment by romancin** [comment]
Is this exactly the same Code?

**Comment by zuosc** [comment]
I try it . And  it can work 。But I am not sure if it is the same

**Comment by romancin** [comment]
Done.
https://github.com/romancin/rutorrent-flood-docker/pull/162
