### ISSUE TITLE
Bandwidth Limiting keeps resetting to 100MB/s (rutorrent)

### ISSUE THREAD

**Issue by adriel** [romancin/rutorrent-flood-docker#9]
In Settings, under "Connection" the "Bandwidth Limiting" settings keeps resetting to 102400 (100MB/s).

I can set it to 0, click OK, and then check in Flood, that the limit has been set to unlimited with the infinite symbol, but then when I refresh the rutrorrent page it'll revert back to 102400/102400.

Any ideas what happening here?

This is on a newly setup docker container.

![image](https://cloud.githubusercontent.com/assets/154217/26517876/7546b4d6-42f6-11e7-896f-ddd5a1657925.png)

**Comment by romancin** [comment]
That limit only applies to certain rutorrent plugins. If you want to limit bandwidth persistently you must do it in .rtorrent.rc file:

download_rate = 0
upload_rate = 0

By default I have this in the container Unlimited.

If you only want to make this changes for rutorrent plugins you can edit this file:
/usr/share/webapps/rutorrent/plugins/throttle/throttle.php

Search this line: @define('MAX_SPEED', 100*1024*1024);

And change value according your needs. That is the value you are seeing in rutorrent.

**Comment by adriel** [comment]
Thanks! Yeah, made a change in the throttle file and it's fixed now.
