### ISSUE TITLE
docker-compose & docker command not working

### ISSUE THREAD

**Issue by 3th3r** [romancin/rutorrent-flood-docker#99]
HI,

I've try to create and test a docker compose for your docker image, but the yml scanner pick up some error:
`ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 4, column 10
[root@onlyoffice-server flood]#
`
I dont understand I've use docker-compose for yeras and this is the first time I've saw qomething like this.
my docker compose file
`version: "3"
services:
   flood_web
      image: romancin/rutorrent-flood:0.9.8
      container_name: flood_web
      ports:
         - "9443:443"
         - "3000:3000"
         - "51415-51415:51415-51415"
      volumes:
         - /home/container/flood/config/:/config
         - /home/container/flood/dowloads/:/downloads
      environment:
         - PGID=1001
         - PUID=1001
         - TZ=Europe/Paris
      restart: "no"
`

Also I've try run a standard command, the services wasn't accessible on any port ............

**Comment by Saboti** [comment]
Hi 3th3r,

for Version 3 your Environment definition is wrong.
Dont use -
Reference: https://docs.docker.com/compose/compose-file/#environment

Regards Saboti

**Comment by 3th3r** [comment]
Yes, indeed, I reread all my "V3" docker-compose files and yes env' varialbe are describe without - 
Sorry I must have mix a v2 template with a v3.

But this do not explain why my docker command line didn't work.
`docker run -d --name=rutorrent-flood \
-v /home/container/flood/config/:/config \
-v /home/container/flood/dowloads/:/downloads \
-e PGID=0 -e PUID=0 -e TZ=Europe/Paris \
-p 9443:443 \
-p 3000:3000 \
-p 51415-51415:51415-51415 \
romancin/rutorrent-flood:latest` 

Thank you for your help, I will test it without -, and try to figure out why my command line dont work.
